#!/usr/bin/env node
const script = process.argv[2]

switch (script) {
  case 'build':
    process.env.NODE_ENV = 'production'
    require('./scripts/build.js')
    break
  case 'dev':
    process.env.NODE_ENV = 'development'
    require('./scripts/dev.js')
    break
  case 'eject':
    require('./scripts/eject.js')
    break
  default:
    console.log(`Unknown script "${script}".`)
    break
}
