#!/usr/bin/env node
const script = process.argv[2]
const eject = require('./scripts/eject.js')
const build = require('./scripts/build.js')
const dev = require('./scripts/dev.js')

switch (script) {
  case 'build':
    build()
    break;
  case 'dev':
    dev()
    break;
  case 'eject':
    eject()
    break;
  default:
    console.log(`Unknown script "${script}".`);
    break;
}